[tool.poetry]
name = "src"
version = "0.1.0"
description = "poetry部署fastapi 并且使用Dockerfile部署"
authors = ["love"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.111.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
